apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deployment
  labels:
    app: MemoryLeak
spec:
  replicas: 1
  selector:
   matchLabels:
     app: service-deployment
  template:
    metadata:
      labels:
        app: service-deployment
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: "52323"
    spec:
      volumes:
        - name: diagnostics       
          emptyDir: {}
        - name: dumps
          emptyDir: {}
      #shareProcessNamespace: true
      containers:
        - name: service-memoryleak
          image: fenixvrn/memoryleak:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: diagnostics
              mountPath: /tmp
            - name: dumps
              mountPath: /dumps              
        - name: service-sidecar-monitor
          image: mcr.microsoft.com/dotnet/monitor:6
          ports:
            - containerPort: 52323
          args: [ "--no-auth", "--urls", "http://*:52323"]
          volumeMounts:            
            - name: diagnostics
              mountPath: /tmp
            - name: dumps
              mountPath: /dumps
---
apiVersion: v1
kind: Service
metadata:
  name: service-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: service-deployment
  ports:
  - name: service-memoryleak
    protocol: TCP
    port: 80
    targetPort: 80
  - name: sidecar-monitor
    protocol: TCP
    port: 52323
    targetPort: 52323
---
apiVersion: v1
kind: Service
metadata:
  name: service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: service-deployment
  ports:
  - name: service-memoryleak
    protocol: TCP
    port: 80
    targetPort: 80
  - name: sidecar-monitor
    protocol: TCP
    port: 52323
    targetPort: 52323
